#pragma once

#include "FuckCompat.h"  // FUCK_API.h + ImGui types (ImTextureID)
#include "WeaponSlots.h"

// Bitmap row icons for the things Font Awesome cannot draw.
//
// ⚠ WHY IMAGES AND NOT A SECOND FONT. Under FLICK the editor's glyphs come out
// of fa-solid-900.ttf EMBEDDED IN FUCK.dll, not out of our own icons.ttf:
// EditorStyle::InitFonts only feeds the dormant ImGuiOverlay path and never
// runs in game, which the log confirms by never printing its font lines. FUCK
// exposes GetFont(kRegular/kLarge) and no way to add one, so no new codepoint
// can reach the screen however carefully it is verified in a cmap. FA5 Free
// Solid has no sword, greatsword, axe or mace, so the weapon rows were reusing
// skull-and-crossbones, a fist, a skull and the generic cube.
//
// FUCK does expose an image API, which its own demo plugins use with PNGs, so
// the rows draw pictures instead. Icons.h and its kAll discipline still govern
// every row that stays a glyph; this is only for the ones that cannot be.
//
// EVERY ACCESSOR MAY RETURN 0 and callers must fall back to their glyph. A
// missing or unreadable PNG then looks exactly like today rather than leaving
// a hole in the column.
namespace OS::IconImages {

    // Lazily loads on first call, from inside the UI frame - FUCK's interface
    // is not available before then. Safe to call every frame.
    // ⚠ WEAPON CLASSES ONLY. The shield had a picture for one commit and went
    // back to Font Awesome's shield-alt (user 2026-08-04): it read cleanly
    // already, and it is an armour slot that merely happens to be listed under
    // Weapons & Shields. Armour slots keep their glyphs.
    [[nodiscard]] ImTextureID ForWeapon(WeaponClass a_class);

    // The hair style row and its dye tile. Neither Font Awesome set has a hair
    // glyph and game-icons has exactly one in 4,239 (`hair-strands`, a scribble
    // at row size), so this one comes from Material Symbols instead - a second
    // source, kept to this single icon, credited beside the PNGs.
    //
    // ⚠ The BODY row is not here. It is a glyph, Icons::kFemale, because Font
    // Awesome does have a feminine figure; only hair needed a picture.
    [[nodiscard]] ImTextureID ForHair();

    // The armour rows Font Awesome cannot draw either, by biped slot BIT (not
    // by the community slot number, which is bit + 30). Returns 0 for every
    // other bit, so the caller's glyph stays in charge of the whole rest of the
    // table.
    //
    // ⚠ FIVE ROWS SHARED THE GENERIC CUBE AND THIS IS WHY. Enumerating the
    // bundled cmap showed FA5 Free Solid has no leg, hip, waist, trousers or
    // shoulder glyph at all, so no codepoint could have fixed them - the same
    // wall the weapon rows hit, with the same answer.
    //
    // ⚠ FOUR PICTURES FOR SEVEN ROWS, ON THIS TABLE'S OWN CONVENTION. Closely
    // related rows already share an icon here: Face and Face (alt) are both
    // kSmile. So both legs take the one leg picture and both pelvis rows take
    // the one pelvis picture; the row LABEL is what separates outer from under,
    // and inventing a second drawing to say "under" would be inventing a
    // distinction the art cannot carry.
    //
    // The two arms share a drawing too, but not a mark: the left one is
    // MIRRORED, so the pair reads as a left and a right rather than as the same
    // fist printed twice. See MirrorSlotBit.
    // The nine-slice chrome frame, generated by tools/make_frame_texture.py.
    //
    // ⚠ NOT A ROW ICON, AND IT IS HERE ANYWAY. This is the one loader in the
    // plugin that turns a PNG beside the mod into a texture, and it already
    // solves the two things that are easy to get wrong: the Data-relative path
    // that resolves wherever the mod manager staged us, and never destroying the
    // store, because FUCK::Image's destructor calls back into a DLL that may
    // already be gone at process exit. A second loader would be a second chance
    // to get both wrong.
    //
    // ⚠ ITS ALPHA IS THE SHAPE AND ITS RGB IS WHITE, so the caller supplies the
    // colour as a tint read from the live theme. See ChamferPanel::FrameImage.
    [[nodiscard]] ImTextureID Frame();

    // The same shape with its INTERIOR in the alpha rather than its outline, so
    // a filled panel can be cut to the curve the frame is cut to. Same file,
    // same generator, same fallback rule.
    [[nodiscard]] ImTextureID FrameFill();

    [[nodiscard]] ImTextureID ForSlotBit(std::uint32_t a_bit);

    // Should that picture be drawn right-to-left? True for Arm (left) only.
    // ⚠ THIS IS WHY THE ARM ROWS ARE PICTURES. Both arms were the same
    // hand-rock glyph, so the left and right rows carried an identical mark,
    // and a glyph cannot be mirrored: text has no UV to swap. One drawing
    // sampled backwards costs nothing and no second PNG.
    [[nodiscard]] bool MirrorSlotBit(std::uint32_t a_bit);

}  // namespace OS::IconImages
